DROP TABLE IF EXISTS companies cascade;
DROP TABLE IF EXISTS projects cascade;
DROP TABLE IF EXISTS projects_users cascade;
DROP TABLE IF EXISTS roles cascade;
DROP TABLE IF EXISTS ticket_priorities cascade;
DROP TABLE IF EXISTS ticket_statuses cascade;
DROP TABLE IF EXISTS ticket_types cascade;
DROP TABLE IF EXISTS tickets cascade;
DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS databasechangelog;
DROP TABLE IF EXISTS databasechangeloglock;
DROP SEQUENCE IF EXISTS companies_id_seq;
DROP SEQUENCE IF EXISTS projects_id_seq;
DROP SEQUENCE IF EXISTS roles_id_seq;
DROP SEQUENCE IF EXISTS ticket_priorities_id_seq;
DROP SEQUENCE IF EXISTS ticket_statuses_id_seq;
DROP SEQUENCE IF EXISTS ticket_types_id_seq;
DROP SEQUENCE IF EXISTS tickets_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;
DROP FUNCTION IF EXISTS generate_api_key();